# Generated by Django 4.2 on 2026-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrecord',
            name='verification_type',
            field=models.CharField(choices=[('FULL', 'Full - Document + Liveness'), ('DOCUMENT_ONLY', 'Document Only')], default='FULL', max_length=20),
        ),
    ]
