# Generated by Django 4.2 on 2026-06-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('entity_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('process_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('registration_code', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('NOT_VERIFIED', 'Not Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('document_result', models.IntegerField(blank=True, null=True)),
                ('liveness_result', models.IntegerField(blank=True, null=True)),
                ('name_match_result', models.IntegerField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Verification Record',
                'verbose_name_plural': 'Verification Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
